### ISSUE TITLE
Controller Node is filtered out of the Nodes collection

### ISSUE THREAD

**Issue by spudwebb** [zwave-js/ZWaveJS.NET#45]
Why does the library filters out the controller node from the Controller.Nodes collection?

`Nodes = Nodes.Where((N) => !N.isControllerNode).ToArray();`

The ZWaveNode class includes some useful information like `ZWaveNode.deviceConfig.label`, `ZWaveNode.deviceConfig.manufacturer`, that we may want to have access to for the controller node.

**Comment by marcus-j-davies** [comment]
Hi @spudwebb.

I filtered out the `Controller` as it differs substantially to a `ZWaveNode`
for instance, A `Controller` will never have the ability to `set`, `get` or configure values - as the Controllers Firmware, is quite different.


But,  with that said, I see no reason why we can't add the `label` and `manufacture` name  to its properties, or Evan add the `DeviceConfig` class - which makes more sense.

I should note: I'm extremely close to releasing V4.
There is a Branch, that represents a potential gateway to a release.

See the diff here.
https://github.com/zwave-js/ZWaveJS.NET/compare/4.0.0...Update-schema-+-fixes

I will be creating a PR for it soon (to target the V4 Branch)
This Branch (soon to be PR'd against V4) does have a 1-2 breaking changes, mainly for renamed methods (since it now uses the latest Schema)

**Comment by marcus-j-davies** [comment]
Fixed in recent commit
